version: '3'
services:
  ui:
    build: ./customassistantui
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://api:8081/api
    depends_on:
      - api
  api:
    build: ./customassistantapi
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db:
    image: "mongo:3.4.20-xenial"
    ports:
      - "27017:27017"