zuul:
  routes:
    api:
      path: /api/**
      url: http://localhost:8081/api
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic